"""empty message

Revision ID: c8f65b8e3cc5
Revises: c052470322c7
Create Date: 2019-10-06 13:31:19.698498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f65b8e3cc5'
down_revision = 'c052470322c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_profesor_especialidad'), 'profesor', ['especialidad'], unique=True)
    op.create_index(op.f('ix_profesor_name'), 'profesor', ['name'], unique=True)
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_index(op.f('ix_profesor_name'), table_name='profesor')
    op.drop_index(op.f('ix_profesor_especialidad'), table_name='profesor')
    # ### end Alembic commands ###
